#if UNITY_EDITOR
using UnityEditor;

using SETB.InnerWorkings;

namespace SETB.UserSide.AutoGenerated
{
    public sealed class SETB_InspectorCreation_AutoGenerated
    {
        //! DO NOT MODIFY THIS CODE. IT IS AUTO GENERATED, CHANGES WILL BE OVERRIDEN.
        //! DO NOT DELETE THIS SCRIPT, IT'S NECESSARY FOR SAUB TO WORK.
	}
}
#endif
