#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using System;

using SETB._CustomEditor.ScriptableObjects;
using static SETB.EditorHelpers;

namespace SETB.InnerWorkings
{
    //[CreateAssetMenu(fileName = "InspectorCreation_InnerWorkings", menuName = "SAUB/Inner WorkingsInspectorCreation_InnerWorkings")]
    public class InspectorCreation_InnerWorkings : ScriptableObject
    {
        #region Variables
        private static InspectorCreation_InnerWorkings _instance = null;
        public static InspectorCreation_InnerWorkings instance
        {
            get
            {
                if (_instance == null) _instance = GetAllAssets<InspectorCreation_InnerWorkings>("InspectorCreation_InnerWorkings")?[0];

                return _instance;
            }
        }


        private const string autoGenerated_fileName = "SETB_InspectorCreation_AutoGenerated";



        [Serializable]
        private class InspectorCreationDataEntry
        {
            public string key;
            public InspectorCreationData[] data;
        }
        [SerializeField] private List<InspectorCreationDataEntry> serializedData = new();

        private Dictionary<string, InspectorCreationData[]> data = new();
        #endregion




        #region Main
        private void OnEnable() => RebuildDictionary();
        #endregion



        #region Logic
        public static string GenerateMethods(InspectorCreationAssets obj, string lastName)
        {
            string key = instance?.Fetch(obj, lastName);
            if (key == null) return key;


            GenerateFile(key);


            return key;
        }

        public string Fetch(InspectorCreationAssets obj, string lastName)
        {
            if (data == null) data = new();


            if (obj == null)
            {
                Debug.LogError("InspectorCreationAssets instance can't be null.");

                return lastName;
            }


            if (lastName == null) lastName = obj.name;

            if (lastName != obj.name)
            {
                RenameKeyInFile(lastName, obj.name);


                data.Remove(lastName);

                lastName = obj.name;
            }


            if (data.ContainsKey(lastName))
                Debug.LogWarning("Repeated name detected, overriding data. Make sure you don't have InspectorCreationAssets instances with repeated names.");
            
            data[lastName] = obj.data;
            SyncSerializedList();


            return lastName;
        }


        #region File manipulation
        private static void GenerateFile(string key)
        {
            var infos = GetAllAssetsWithPath<MonoScript>(autoGenerated_fileName);

            if (infos == null || infos.Count == 0)
            {
                Debug.LogError($"No MonoScript found with name: {autoGenerated_fileName}");
                return;
            }

            var info = infos[0];


            string path = info.path;
            string fileText = File.ReadAllText(path);

            var d = instance?.data[key];
            
            if (d == null)
            {
                Debug.LogError("Code generation failed.");

                return;
            }


            string startTag = $"// <AUTO_GENERATED_START:{key}>";
            string endTag = $"// <AUTO_GENERATED_END:{key}>";

            if (!fileText.Contains(startTag))
            {
                int insertIndex = GetClassInsertIndex(fileText);
                if (insertIndex == -1) return;

                fileText = fileText.Insert(insertIndex, $"\n\t\t{startTag}\n\t\t{endTag}\n");
            }

            
            StringBuilder builder = new StringBuilder();

            for (int i = 0; i < d.Length; i++)
            {
                var item = d[i];

                if (item == null || item.prefab == null) continue;

                string methodName = item.prefab.name.Replace(" ", "");

                builder.AppendLine($"\t\t[MenuItem(\"GameObject/{item.path}\", {item.validateFunction.ToString().ToLower()}, {item.priority})]");
                builder.AppendLine($"\t\tprivate static void {methodName}(MenuCommand menuCommand)");
                builder.AppendLine("\t\t{");
                builder.AppendLine($"\t\t\tInspectorCreation_InnerWorkings.instance?.CreatePrefabFromIndex(\"{key}\", {i}, menuCommand);");
                builder.AppendLine("\t\t}");
            }

            string newBlock = $"\n\t\t{startTag}\n{builder}\t\t{endTag}";


            int startIndex = fileText.IndexOf(startTag);
            int endIndex = fileText.IndexOf(endTag) + endTag.Length;

            fileText = fileText.Remove(startIndex, endIndex - startIndex);
            fileText = fileText.Insert(startIndex, newBlock);

            
            int classEndIndex = GetClassInsertIndex(fileText);
            if (classEndIndex == -1) return;

            fileText = fileText.Remove(classEndIndex, 1);
            fileText = fileText.Insert(classEndIndex, $"\t}}");

            File.WriteAllText(path, fileText);


            AssetDatabase.Refresh();
        }

        private static int GetClassInsertIndex(string fileText)
        {
            const string classHeader = "public sealed class SETB_InspectorCreation_AutoGenerated";


            int classIndex = fileText.IndexOf(classHeader);
            if (classIndex == -1)
            {
                Debug.LogError("AutoGenerated class not found.");
                return -1;
            }


            int openBrace = fileText.IndexOf("{", classIndex);
            if (openBrace == -1)
            {
                Debug.LogError("Class opening brace not found.");
                return -1;
            }


            int depth = 0;

            for (int i = openBrace; i < fileText.Length; i++)
            {
                if (fileText[i] == '{') depth++;
                else if (fileText[i] == '}') depth--;

                if (depth == 0) return i;
            }


            Debug.LogError("Class closing brace not found.");
            return -1;
        }

        private static void RenameKeyInFile(string oldKey, string newKey)
        {
            if (string.IsNullOrEmpty(oldKey) || oldKey == newKey) return;


            var infos = GetAllAssetsWithPath<MonoScript>(autoGenerated_fileName);

            if (infos == null || infos.Count == 0)
            {
                Debug.LogError($"No MonoScript found with name: {autoGenerated_fileName}");
                return;
            }

            var info = infos[0];
            if (info.asset == null) return;


            string path = info.path;
            string text = File.ReadAllText(path);

            string oldStart = $"// <AUTO_GENERATED_START:{oldKey}>";
            string oldEnd   = $"// <AUTO_GENERATED_END:{oldKey}>";

            string newStart = $"// <AUTO_GENERATED_START:{newKey}>";
            string newEnd   = $"// <AUTO_GENERATED_END:{newKey}>";

            if (!text.Contains(oldStart)) return;

            text = text.Replace(oldStart, newStart);
            text = text.Replace(oldEnd, newEnd);

            File.WriteAllText(path, text);


            AssetDatabase.Refresh();
        }
        #endregion
        #endregion


        
        #region Data handling
        private void RebuildDictionary()
        {
            data = new Dictionary<string, InspectorCreationData[]>();

            if (serializedData == null) return;

            for (int i = 0; i < serializedData.Count; i++)
            {
                var entry = serializedData[i];
                if (entry == null || string.IsNullOrEmpty(entry.key)) continue;

                data[entry.key] = entry.data;
            }
        }


        private void SyncSerializedList()
        {
            serializedData.Clear();

            foreach (var kvp in data)
            {
                serializedData.Add(new InspectorCreationDataEntry
                {
                    key = kvp.Key,
                    data = kvp.Value
                });
            }

            EditorUtility.SetDirty(this);
        }
        #endregion



        #region Prefab Creation
        public void CreatePrefabFromIndex(string name, int index, MenuCommand menuCommand)
            => CreatePrefab(data[name]?[index]?.prefab, menuCommand, data[name]?[index]?.unpack);

        public static void CreatePrefab(GameObject prefab, MenuCommand menuCommand, bool? unpack)
        {
            if (prefab == null)
            {
                Debug.LogError($"Prefab is null.");

                return;
            }
            if (unpack == null)
            {
                Debug.LogError($"Unpack bool is null.");

                return;
            }
            

            GameObject instance = PrefabUtility.InstantiatePrefab(prefab) as GameObject;

            GameObjectUtility.SetParentAndAlign(instance, menuCommand.context as GameObject);
            Undo.RegisterCreatedObjectUndo(instance, "Create Prefab");

            if (unpack.Value)
            {
                PrefabUtility.UnpackPrefabInstance(
                    instance,
                    PrefabUnpackMode.Completely,
                    InteractionMode.UserAction
                );
            }

            Selection.activeObject = instance;
        }
        #endregion
    }
}
#endif
